name: CD Fake
on:
    workflow_dispatch:
jobs:
    deploy-fake:
        runs-on: ubuntu-latest
        steps:
            - name: Fake do deploy em ambiente
              run: echo "Deploy em ambiente ${{ vars.AMBIENTE_DEPLOY }}"