name: CD Fake
on:
    workflow_dispatch:
jobs:
    deploy-fake-homologacao:
        runs-on: ubuntu-latest
        environment: homologacao
        steps:
            - name: Fake do deploy em ambiente
              run: echo "Deploy em ambiente ${{ vars.AMBIENTE_DEPLOY }}"
    teste-fake:
        runs-on: ubuntu-latest
        needs: [deploy-fake-homologacao]
        environment: homologacao
        steps:
            - name: Fake do teste em ambiente
              run: echo "teste em ambiente ${{ vars.AMBIENTE_DEPLOY }}"
    deploy-fake-producao:
        runs-on: ubuntu-latest
        needs: [teste-fake]
        environment: producao
        steps:
            - name: Fake do deploy em ambiente
              run: echo "Deploy em ambiente ${{ vars.AMBIENTE_DEPLOY }}"